@startuml Sort Command State Diagram

[*] --> FieldSelection
FieldSelection --> [*] : Cancelled
FieldSelection --> OrderSelection : Field chosen

OrderSelection --> [*] : Cancelled
OrderSelection --> [*] : Order chosen (return args)
@enduml